version: '3.7'

services:
  currency-exchange:
    image: sg-micro-service-docker/v2-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE:http://naming-server:8761/eureka:
      SPRING.ZIPKIN.BASEURL: http://localhost:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  naming-server:
    image: sg-micro-service-docker/v2-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8762:8762"
    networks:
      - currency-network

  api-gateway:
   image: sg-micro-service-docker/v2-api-gateway:0.0.1-SNAPSHOT
   mem_limit: 700m
   ports:
    - "8760:8760"
   networks:
    - currency-network
   depends_on:
    - naming-server
    - rabbitmq
   environment:
    EUREKA.CLIENT.SERVICEURL.DEFAULTZONE:http://naming-server:8761/eureka:
    SPRING.ZIPKIN.BASEURL: http://localhost:9411/
    RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    SPRING_RABBITMQ_HOST: rabbitmq
    SPRING_ZIPKIN_SENDER_TYPE: rabbit

  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - currency-network
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq

networks:
  currency-network: